name: FFHQ
save_dir: ./output
G_reg_interval: 4
D_reg_interval: 16
metrics: []
data_path: 
use_labels: False
max_size: null
xflip: True
resolution: 128
z_dim: 512
w_dim: 512
num_layers: 2
channel_base: 16384
channel_max: 512
r1: 10.
glr: 0.002
gbeta1: 0
gbeta2: 0.99
geps: 0.00000001
dlr: 0.002
dbeta1: 0
dbeta2: 0.99
deps: 0.00000001
ckpt_path: ./checkpoints
gpu: True
num_gpus: 1
print_freq: 1
display_freq: 1
save_freq: 1
eval_freq: 5000
eval_path: ./eval/FFHQ
eval_orig: ./eval/FFHQ_orig
disable_eval: False
eval_batch: 50
num_epoch: 50
batch_size: 8
sample_size: 64
size: 128
ema_kimg: 10
g_pretrained: ./checkpoints/FFHQ/G.pkl
d_pretrained: ./checkpoints/FFHQ/D.pkl
g_ema_pretrained: ./checkpoints/FFHQ/G_ema.pkl
resume: True
w_shift: null
channel_multiplier: 2
lr_mlp: 0.01
n_mlp: 8
size: 128
fixed_z: null
vis_path: ./visual
device: 1
truncation_mean: 4096
truncation: 0.5
diffaug_policy: ''
transform_real: to3ch
transform_fake: to3ch
ganmode: softplus
eval_size: 7000
ada_target: 0.6
xflip: 1
rotate90: 1
xint: 1
scale: 1
rotate: 1
aniso: 1
xfrac: 1
brightness: 1
contrast: 1
lumaflip: 1
hue: 1
saturation: 1
augment: True
augment_p: 0.
ada_interval: 4
ada_kimg: 500
use_wandb: False
style_mixing_prob: 0.9
path_batch_shrink: 2
path_regularize: 2
